<?php

namespace KeyHoang\OrgModule\Controllers;

use App\Base\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use KeyHoang\OrgModule\Models\User;
use KeyHoang\OrgModule\Services\UserService;

class UserController extends Controller
{

    /**
     * @var UserService $service
     */
    public $service;

    /**
     * @param User   $model
     * @param string $serviceName
     */
    public function __construct(private readonly User $model, string $serviceName = UserService::class)
    {
        parent::__construct($this->model, $serviceName);
    }

    /**
     * Display a listing of the User.
     *
     * @Date   Sep 16, 2023
     * @return JsonResponse
     */

    public function index(): JsonResponse
    {
        return parent::index();
    }

    /**
     * Display the specified User.
     *
     * @Date  Sep 16, 2023
     *
     * @param $id
     *
     * @return JsonResponse
     */

    public function show($id): JsonResponse
    {
        return response()->json($this->service->getById($id));
    }

    /**
     * Store a newly created User in storage.
     *
     * @Date  Sep 16, 2023
     *
     * @param Request $request
     *
     * @return JsonResponse
     */

    public function store(Request $request): JsonResponse
    {
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * Update the specified User in storage.
     *
     * @Date        Sep 16, 2023
     *
     * @param         $id
     * @param Request $request
     *
     * @return JsonResponse
     */

    public function update($id, Request $request): JsonResponse
    {
        return parent::update($id, $request); // todo: change the autogenerated stub
    }

    /**
     * Put Update the specified User in storage.
     *
     * @Date        Sep 16, 2023
     *
     * @param         $id
     * @param Request $request
     *
     * @return JsonResponse
     */

    public function putUpdate($id, Request $request): JsonResponse
    {
        return parent::putUpdate($id, $request); // TODO: Change the autogenerated stub
    }

    /**
     * Remove the specified User from storage.
     *
     * @Date        Sep 16, 2023
     *
     * @param $id
     *
     * @return JsonResponse
     */

    public function destroy($id): JsonResponse
    {
        return parent::destroy($id); // TODO: Change the autogenerated stub
    }

    /**
     * Remove the multiple specified User from storage by ids
     *
     * @Author      yaangvu
     * @Date        Sep 16, 2023
     *
     * @param Request $request
     *
     * @return JsonResponse
     */

    public function deleteByIds(Request $request): JsonResponse
    {
        return parent::deleteByIds($request); // TODO: Change the autogenerated stub
    }
}
